blank_issues_enabled: false
contact_links:
  - name: "⛔ Support or Question"
    url: https://discord.gg/bpmXfz5
    about: "Please don't use GitHub for asking questions. If you simply have a question, then the Discord chat is the best place to ask it. You will get an answer there much faster than here!"
